import {  Montserrat, Poppins } from "next/font/google";
import "./globals.css";


const poppins= Poppins({
  variable:"--font-poppins",
  subsets:["latin"],
  weight:["400","500","600","700","800"]
});
export const montserrat= Montserrat({
  variable:"--font-montserrat",
  subsets:["latin"],
  weight:["400","500","600","700","800"]
})
export const metadata = {
  title: "Dragon News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${poppins.className}  min-h-full flex flex-col`}><main className="container my-2 mx-auto px-10">{children}</main></body>
    </html>
  );
}
